### ISSUE TITLE
About video features

### ISSUE THREAD

**Issue by onion-lynn** [zhiyuanhubj/Long_form_VideoQA#1]
Hi, I would like to ask how your video features are extracted? What are the input dimensions?

**Comment by nguyentthong** [comment]
Hi,

You can find video features of our Ego-QA and MAD-QA datasets in [this link](https://drive.google.com/drive/folders/1T22ixENJvTn6wrARj8KX5dr6hYsPB9D6?usp=drive_link).

Regards,
Thong

**Comment by onion-lynn** [comment]
Thank you very much for your prompt reply!! So if I want to use my own data set on this model, how do I extract the features?

**Comment by nguyentthong** [comment]
You can look into the `extract_clip_features.py` file I have just uploaded in the google drive link.

**Comment by onion-lynn** [comment]
> 您可以在 google drive 链接中查看我刚刚上传的文件。`extract_clip_features.py`

Thank you very much for your reply! I found that the `VideoCLIPDataset` function mentioned in line 20 is missing in the `extract_clip_features.py` file. Could you please add it?
