### ISSUE TITLE
About reproducing the experimental results

### ISSUE THREAD

**Issue by onion-lynn** [zhiyuanhubj/Long_form_VideoQA#4]
Thank you so much for your remarkable work! I have recently been attempting to replicate the results of your experiment using the Ego-QA dataset. However, I'm encountering a somewhat perplexing issue.

I adhered strictly to the parameters outlined in your train script and utilized the  
`CLIP_B32_frames_features_5fps_512_frames_per_video.h5` file you supplied for the features.
```python
python main_egoqa.py --checkpoint_dir=egoqaV2 \
	--feature_dir='/ai/Long_vqa/egoqa_madqa/'  \
	--dataset=egoqa \
	--mc=5 \
	--bnum=5 \
	--epochs=30 \
	--lr=0.00004 \
	--qmax_words=30 \
	--amax_words=38 \
	--max_feats=32 \
	--batch_size=64 \
	--batch_size_val=64 \
	--num_thread_reader=8 \
	--mlm_prob=0 \
	--n_layers=2 \
	--embd_dim=512 \
	--ff_dim=1024 \
	--dropout=0.3 \
	--seed=400 \
	--topk-selector-dataloading 0 \
	--num-frames-in-feature-file 512 \
	--save_dir='/ai/Long_vqa/output/ego_qa/v2/'
``` 

The trained model appears to be functioning as expected during the experiment, but the test results are incredibly unusual. 
![image](https://github.com/user-attachments/assets/52a653f3-ca5c-42e2-91b0-eb5550402fe7)
Specifically, the accuracy (acc) obtained from the test set is abnormally high, as shown in the attached figure.![image](https://github.com/user-attachments/assets/87b70fbc-7f38-4521-8264-36452bd49dac)

Have you come across something similar before or can suggest some tweaks to help resolve this? Any guidance you can provide would be greatly appreciated.

**Comment by nguyentthong** [comment]
Dear @onion-lynn, we have examined and there is some certain data leakage. We have corrected the data to remove the leakage. Sorry for any inconvenience.

**Comment by onion-lynn** [comment]
Thank you very much for your prompt reply!! I downloaded your updated train.csv, val.csv and test.csv files as soon as I received your reply. I retrained the model, but I don't know what the problem is. The model does not converge well. Do you have any good suggestions on how to modify it?
train：
![屏幕截图 2024-10-09 235411](https://github.com/user-attachments/assets/1106ef41-9ae8-47b8-92bb-90dc5f92bf62)
test：
![屏幕截图 2024-10-09 235430](https://github.com/user-attachments/assets/fd87fb42-292b-4ba0-8d66-bf0205be1bd1)

**Comment by nguyentthong** [comment]
hi @onion-lynn, thank you for your note. We will try to tackle your raised problem in our future research.
